/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandReviewRouteImport } from './routes/brand-review'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ForBrandsApplyRouteImport } from './routes/for-brands.apply'
import { Route as LookLookIdRouteImport } from './routes/look.$lookId'
import { Route as AuthenticatedBrandDashboardRouteImport } from './routes/_authenticated/brand/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandReviewRoute = BrandReviewRouteImport.update({
  id: '/brand-review',
  path: '/brand-review',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBrandsApplyRoute = ForBrandsApplyRouteImport.update({
  id: '/for-brands/apply',
  path: '/for-brands/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const LookLookIdRoute = LookLookIdRouteImport.update({
  id: '/look/$lookId',
  path: '/look/$lookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBrandDashboardRoute =
  AuthenticatedBrandDashboardRouteImport.update({
    id: '/brand/dashboard',
    path: '/brand/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-review': typeof BrandReviewRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/for-brands/apply': typeof ForBrandsApplyRoute
  '/look/$lookId': typeof LookLookIdRoute
  '/brand/dashboard': typeof AuthenticatedBrandDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand-review': typeof BrandReviewRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/for-brands/apply': typeof ForBrandsApplyRoute
  '/look/$lookId': typeof LookLookIdRoute
  '/brand/dashboard': typeof AuthenticatedBrandDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/brand-review': typeof BrandReviewRoute
  '/create': typeof CreateRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/for-brands/apply': typeof ForBrandsApplyRoute
  '/look/$lookId': typeof LookLookIdRoute
  '/_authenticated/brand/dashboard': typeof AuthenticatedBrandDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brand-review'
    | '/create'
    | '/discover'
    | '/explore'
    | '/profile'
    | '/for-brands/apply'
    | '/look/$lookId'
    | '/brand/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brand-review'
    | '/create'
    | '/discover'
    | '/explore'
    | '/profile'
    | '/for-brands/apply'
    | '/look/$lookId'
    | '/brand/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/brand-review'
    | '/create'
    | '/discover'
    | '/explore'
    | '/profile'
    | '/for-brands/apply'
    | '/look/$lookId'
    | '/_authenticated/brand/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BrandReviewRoute: typeof BrandReviewRoute
  CreateRoute: typeof CreateRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRoute
  ProfileRoute: typeof ProfileRoute
  ForBrandsApplyRoute: typeof ForBrandsApplyRoute
  LookLookIdRoute: typeof LookLookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-review': {
      id: '/brand-review'
      path: '/brand-review'
      fullPath: '/brand-review'
      preLoaderRoute: typeof BrandReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-brands/apply': {
      id: '/for-brands/apply'
      path: '/for-brands/apply'
      fullPath: '/for-brands/apply'
      preLoaderRoute: typeof ForBrandsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/look/$lookId': {
      id: '/look/$lookId'
      path: '/look/$lookId'
      fullPath: '/look/$lookId'
      preLoaderRoute: typeof LookLookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/brand/dashboard': {
      id: '/_authenticated/brand/dashboard'
      path: '/brand/dashboard'
      fullPath: '/brand/dashboard'
      preLoaderRoute: typeof AuthenticatedBrandDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrandDashboardRoute: typeof AuthenticatedBrandDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrandDashboardRoute: AuthenticatedBrandDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BrandReviewRoute: BrandReviewRoute,
  CreateRoute: CreateRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRoute,
  ProfileRoute: ProfileRoute,
  ForBrandsApplyRoute: ForBrandsApplyRoute,
  LookLookIdRoute: LookLookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
